-- CAJERO
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.facturas TO ROL_CAJERO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.detalles TO ROL_CAJERO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.detallefactura TO ROL_CAJERO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.abonos TO ROL_CAJERO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.facturasporpagar TO ROL_CAJERO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.clientes TO ROL_CAJERO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.personas TO ROL_CAJERO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.servicios TO ROL_GERENTE;

-- COORDINADOR
GRANT SELECT ANY TABLE TO COORDINADOR;
GRANT INSERT ANY TABLE TO COORDINADOR;
GRANT DELETE ANY TABLE TO COORDINADOR;
GRANT UPDATE ANY TABLE TO COORDINADOR;

--GERENTE
GRANT DBA TO GERENTE;

-- ENCARGADO DE INVENTARIO
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.inventario TO ROL_ENCARGADO_INVETARIO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.bodegas TO ROL_ENCARGADO_INVETARIO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.lotes TO ROL_ENCARGADO_INVETARIO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.sucursales TO ROL_ENCARGADO_INVETARIO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.productos TO ROL_ENCARGADO_INVETARIO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.codigobarras TO ROL_ENCARGADO_INVETARIO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.familias TO ROL_ENCARGADO_INVETARIO;
GRANT SELECT, INSERT, UPDATE, DELETE ON shernandez.proveedores TO ROL_ENCARGADO_INVETARIO;

GRANT EXECUTE, DEBUG ON prc_agregardetallefactura TO usuario_cajero;
GRANT EXECUTE, DEBUG ON prc_enviarcorreo TO usuario_cajero;
GRANT EXECUTE, DEBUG ON prc_abonos TO usuario_cajero;
GRANT EXECUTE, DEBUG ON prc_devolucion TO usuario_cajero;
GRANT EXECUTE, DEBUG ON prc_agregardetallefactura TO usuario_cajero;
